### ISSUE TITLE
is wookie setup to use the latest cl-async

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/wookie#64]
Im having issues with wookie using latest cl-async/blackbird and was wondering if its supported before I dive into it.

**Comment by orthecreedence** [comment]
Sorry, things are kind of in flux. Check out the fast-http branch of Wookie. Really, everything in cl-async that got pushed to QL recently was an error on my part, I really should have been using a separate branch. So QL has a now-somewhat-outdated version of cl-async that works with *some* of my other projects but not others...it's a mess.

I'm hoping to have everything back in sync soon. I've been using the fast-http branch of Wookie for quite some time now without problems. I can't remember if there are any breaking API changes (I don't think so) but if you run into anything, please let me know.

**Comment by nightshade427** [comment]
aweome will do, thanks!

**Comment by nightshade427** [comment]
Is error handling different now?
```lisp
caught ERROR:                                                                                                         
;   READ error during COMPILE-FILE:                                                                                     
;                                                                                                                       
;     Symbol "*ERROR-HANDLER*" not found in the WOOKIE package.                                                         
;                                                                                                                       
;       Line: 84, Column: 28, File-Position: 2580                                                                       
;                                                                                                                       
;       Stream: #<SB-SYS:FD-STREAM for "file /root/Dropbox/alchemy/server.lisp"                                         
;                 {10143F9F43}>
```

**Comment by nightshade427** [comment]
Actually your default error handler looks exactly like mine!! haha

**Comment by nightshade427** [comment]
But, how do I set it up in case I need to in the future?

**Comment by orthecreedence** [comment]
The `listener` class now takes an `:event-cb` argument which should get error forwarded to it. If you want to have error bubble to the top level (good for debugging) then set `*wookie-config:*debug-on-error*` to `t`. Sorry, this is all undocumented still...been a busy few months =]

**Comment by nightshade427** [comment]
Awesome, thanks. :)
