### ISSUE TITLE
urlencoded newlines errors

### ISSUE THREAD

**Issue by nightshade427** [orthecreedence/wookie#72]
http://fqdn.com?data=test%0d%0athis

results in:

There was an error processing your request: The string "test%0d%0athis" is not a valid urlencoded string.

**Comment by nightshade427** [comment]
here is my temp workaround if that helps

https://github.com/nightshade427/wookie/commit/9c83b23afe6d1c2503b425011a59239ffae7d96a

**Comment by orthecreedence** [comment]
Your temp workaround is prefect. Merged in your master version to mine (including the "json" file type for the directory router, another good change). Thanks!
