### ISSUE TITLE
Unable to load any of the alternatives: ("libuv.dylib")

### ISSUE THREAD

**Issue by JacksonGariety** [orthecreedence/wookie#73]
New to common lisp so probably just don't something basically wrong.

1. `$ ccl`
2. `* (ql:quickload :wookie)`

    Unable to load any of the alternatives:
        ("libuv.dylib")
     [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]

Thanks. Looking forward to getting this working.

**Comment by PuercoPop** [comment]
Do you have libuv installed in your system? (libuv is a C library)

**Comment by JacksonGariety** [comment]
@PuercoPop I do.

The file needed is `libuv.1.dylib`. It lives in `/usr/local/Cellar/libuv/1.8.0/lib/` and it's symlinked to `libuv.dylib` in the same location.

**Comment by JacksonGariety** [comment]
I think the issue is part of cl-async, though: https://github.com/orthecreedence/cl-async/issues/138

**Comment by PuercoPop** [comment]
I no longer have a Mac, but when I did homebrew installed the libraries in /usr/local/lib. If this has changed it is a matter of adding the location to the path

**Comment by JacksonGariety** [comment]
@PuercoPop where is that path?

**Comment by JacksonGariety** [comment]
There *must* be a better way to access libuv than this: https://github.com/orthecreedence/cl-libuv/blob/220b87f5bce71c2238d61269f0f8a7bad044b15d/lib.lisp

I'm not too familiar with CL but listing some generic paths seems odd to me.

**Comment by orthecreedence** [comment]
Closing in favor of https://github.com/orthecreedence/cl-async/issues/138 (this is a cl-async issue, not Wookie)
