### ISSUE TITLE
Does not build - urlencode api issue?

### ISSUE THREAD

**Issue by quicklisp** [orthecreedence/wookie#85]
I get this:

    ; file: /home/quicklisp/quicklisp-controller/dist/build-cache/wookie/f61e1c13eb11deacb1a3e8e556eb21aa9cb2e228/wookie-20181011-git/parser.lisp
    ; in: DEFUN SETUP-PARSER
    ;     (DO-URLENCODE:URLDECODE (QURI.URI:URI-PATH WOOKIE::PARSED-URI) :LENIENTP T)
    ; 
    ; caught WARNING:
    ;   :LENIENTP is not a known argument keyword.

**Comment by orthecreedence** [comment]
Can you try this again?

**Comment by quicklisp** [comment]
Doesn't help, sorry, since it's a compile-time warning, not a runtime warning.

**Comment by quicklisp** [comment]
You can see the problem if you try with sbcl and use `:verbose t` on quickloading.

**Comment by orthecreedence** [comment]
Ok, what about now?

**Comment by quicklisp** [comment]
Sorry, SBCL is too smart for that and can tell the call is to the same function as before.

**Comment by orthecreedence** [comment]
God damnit. Worked wth CCL. Do you think something like

```lisp
(let* ((fn (funcall (lambda () 'do-urlencode:urldecode)))
       (path (funcall 'fn ...))
...)
```

has a chance?

**Comment by quicklisp** [comment]
Not sure, sorry. How about just leaving off the keyword argument entirely, since it is not available on the new API anyway?

**Comment by orthecreedence** [comment]
Because if someone is using the old version without the keyword, the url parsing breaks quite often. But yeah, might as well just take it out.

**Comment by orthecreedence** [comment]
K should be fixed. Thanks for the help.
