### ISSUE TITLE
System "plugin" not found

### ISSUE THREAD

**Issue by C-Entropy** [orthecreedence/wookie#90]
I just reinstall my sbcl, asdf, and quicklisp and do the followings:
```
(ql:quickload :wookie)

(defpackage :my-website
  (:use :cl :wookie :wookie-plugin-export))

(in-package :my-website)

;; load Wookie's core plugins. much of Wookie's functionality is written as
;; plugins which can be enabled/disabled/overwritten it desired.
(load-plugins)
```
and then a error occur when `(load-plugins)`:
`System "plugin" not found`
I have also tried the code from github, and error remain.

**Comment by akanouras** [comment]
This is fixed by #93 .

**Comment by C-Entropy** [comment]
Looks fixed to me, great thanks!

**Comment by not-null-nil** [comment]
Looks fixed to me, great thanks!
